orbs:
  rookout-node: rookout/rookout-node@0.0.2

description: "A circle-ci job that uses rookout-node to debug a node command"
  
jobs:
  buggy_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - rookout-node/run_script:
          users_scipt: "~/Rookout/example_app.js param1"

version: 2.1
workflows:
  main:
    jobs:
      - buggy_job