orbs:
  rookout-node: rookout/rookout-node@0.0.2

description: "A circle-ci job that uses rookout-node to debug a node command"
  
jobs:
  my_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - rookout-node/run_script:
          users_script: "node --trace-warnings --trace-sync-io --title=xxxxxxx ~/Rookout/examples/example_app.js"
          rookout_tags: "asdf;asdf2"
      - rookout-node/run_script:
          users_script: "node ~/Rookout/examples/example_app.js"
      - rookout-node/run_script:
          users_script: "~/Rookout/examples/example_app.js"
      - rookout-node/run_script:
          users_script: "~/Rookout/examples/example_app.js p1 p2 p3"

version: 2.1
workflows:
  main:
    jobs:
      - my_job