references:
  auth_google: &auth_google
    run:
      command: |
        sudo apt-get update && sudo apt-get install lsb-core 
        export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install google-cloud-sdk
        echo ${GOOGLE_AUTH} > gcp-key.json && gcloud auth activate-service-account --key-file gcp-key.json

orbs:
  codecov: circleci/codecov-clojure@0.0.4
  my-orb:
    description: "A circle-ci orb that loads rookout-node to your program"
    jobs:
      myjob:
        executor: default
        parameters:
          rookout_tags:
            type: string
          users_script:
            type: string
        steps:
          - *auth_google
          - install_rook_if_needed
          - run_users_script:
              rookout_tags: <<parameters.rookout_tags>>
              users_script: <<parameters.users_script>>
            
    executors:
      default:
        docker:
          - image: circleci/node:10
          
    commands:
      install_rook_if_needed:
        steps:
          - run: 
              command: | 
                if ! which rookout-node; then
                  gsutil cp gs://rookout-rooks-artifacts/rooks-nodejs/0.1.29/0.1.29+8335d4/rookout-0.1.29.tgz .
                  sudo npm install --unsafe-perm -g rookout-0.1.29.tgz
                fi
      run_users_script:
        parameters:
          rookout_tags:
            type: string
            default: "$REPONAME;$CIRCLE_JOB;circle-ci"; 
          users_script:
            type: string
        steps:
          - run:
              environment:
                ROOKOUT_ROOK_TAGS=<<parameters.rookout_tags>>
              command: | 
                env
                
                cd /tmp
                sudo npm link rookout
                rookout-node <<parameters.users_script>>


version: 2.1
workflows:
  main:
    jobs:
      - my-orb/myjob:
          users_script: "node /tmp/testRookout.js"