version: 3

jobs:
  checkout_code:
    docker:
      - image: python:2.7
    working_directory: ~/Rookout
    steps:
      - run: echo "hello world"
      
workflows:
  version: 2
  run-pipeline:
    jobs:
      - checkout_code
      