references:
  auth_google: &auth_google
    run:
      command: |
        sudo apt-get update && sudo apt-get install lsb-core 
        export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get install google-cloud-sdk
        echo ${GOOGLE_AUTH} > gcp-key.json && gcloud auth activate-service-account --key-file gcp-key.json

orbs:
  codecov: circleci/codecov-clojure@0.0.4
  my-orb:
    description: "A circle-ci orb that loads rookout-node to your program"
    jobs:
      myjob:
        executor: default
        parameters:
          rookout_token:
            type: string
          rookout_tags:
            type: string
          users_script:
            type: string
        steps:
          - *auth_google
          - install_rook_if_needed
          - run_users_script:
              rookout_token1: <<parameters.rookout_token>>
              rookout_tags1: <<parameters.rookout_tags>>
              users_script1: <<parameters.users_script>>
            
    executors:
      default:
        docker:
          - image: circleci/node:10
          
    commands:
      install_rook_if_needed:
        steps:
          - run: 
              command: | 
                if ! which rookout-node; then
                  gsutil cp gs://rookout-rooks-artifacts/rooks-nodejs/0.1.29/0.1.29+db44ee/rookout-0.1.29.tgz .
                  sudo npm install --unsafe-perm -g rookout-0.1.29.tgz
                fi
      run_users_script:
        parameters:
          rookout_token1:
            type: string
          rookout_tags1:
            type: string
          users_script1:
            type: string
        steps:
          - run:
              command: | 
                echo "<<parameters.rookout_token1>>"
                echo "<<parameters.rookout_tags1>>"
                echo "<<parameters.users_script1>>"
                cd /tmp
                sudo npm link rookout
                node rookout-node


version: 2.1
workflows:
  main:
    jobs:
      - my-orb/myjob:
          name: mybuild2
          rookout_token: "1234"
          rookout_tags: "orb;benk"
          # TODO:: if script starts with node - strip it
          users_script: "node /tmp/testRookout.js"
