version: 3

notify:
  webhooks:
    - url: https://hooks.slack.com/services/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
  branches:
    only:
      - master

references:
  docker_auth: &docker_auth
    auth:
      username: _json_key
      password: $GOOGLE_AUTH

  checkout_default_wd: &checkout_default_wd
    checkout:
      path: ~/Rookout

  setup_cache: &setup_cache
    restore_cache:
      keys:
        - v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  setup_workspace: &setup_workspace
    attach_workspace:
      at: ~/Rookout

  setup_docker: &setup_docker
    setup_remote_docker:
      docker_layer_caching: true

  persist_to_buid_rook_dist: &persist_to_buid_rook_dist
    persist_to_workspace:
      root: .
      paths:
        - build/rook/dist

  artifact_buid_rook_dist: &artifact_to_buid_rook_dist
    store_artifacts:
      path: build/rook/dist

  setup_build_tools: &setup_build_tools
    run:
      command: |
        mkdir -p ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        pip install -U -e git+ssh://git@github.com/Rookout/build_tools.git#egg=rookout_build_tools

  setup_env_var: &setup_env_var
    run:
      command: |
        cat ~/Rookout/workspace/VERSION >> $BASH_ENV

  auth_google: &auth_google
    run:
      command: |
        echo ${GOOGLE_AUTH} > gcp-key.json && gcloud auth activate-service-account --key-file gcp-key.json
        gcloud --quiet config set project ${GOOGLE_PROJECT_ID} && gcloud docker --authorize-only
        cat ~/Rookout/workspace/VERSION >> $BASH_ENV

  requires_unitests:
    requires:
      - openjdk7_unittests
      - openjdk8_unittests
      - python_test_27
      - python_test_35
      - python_test_36
      - python_test_37
      - pypy2_test
      - pypy3_test

  requires_packages_test: &requires_packages_test
    requires:
      - openjdk7_unittests
      - openjdk8_unittests
      - python_test_27
      - python_test_35
      - python_test_36
      - python_test_37
      - pypy2_test
      - pypy3_test
      - rook_package_test_java7
      - rook_package_test_java8
      - rook_package_test_python2
      - rook_package_test_python35
      - rook_package_test_python36
      - rook_package_test_python37
      - rook_package_test_pypy
      - rook_package_test_node4
      - rook_package_test_node6
      - rook_package_test_node8
      - rook_package_test_node10

  requires_build_finish: &requires_build_finish
    requires:
      - build_demo_image

    filters:
      branches:
        only: master

  requires_hold: &requires_hold
    requires:
      - hold

  requires_python_tests: &requires_python_tests
    requires:
      - python_test_27
      - python_test_35
      - python_test_36
      - python_test_37
      - pypy2_test
      - pypy3_test

  load_gradle_cache: &load_gradle_cache
    restore_cache:
      keys:
        -  java-dependencies-new-{{ checksum "/root/Rookout/rooks/jvm/rook/build.gradle" }}

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: java-dependencies-new-{{ checksum "/root/Rookout/rooks/jvm/rook/build.gradle" }}
      paths:
        - /root/.gradle

jobs:
  checkout_code:
    docker:
      - image: python:2.7
    working_directory: ~/Rookout
    steps:
      - *checkout_default_wd
      - *setup_build_tools
      - attach_workspace:
          at: ~/Rookout
      - add_ssh_keys
      - run: mkdir -p  /root/Rookout/workspace
      - run: echo $GOOGLE_AUTH > gcp-key.json
      - run: rbt version get-next > /root/Rookout/workspace/VERSION
      - run: cat ~/Rookout/workspace/VERSION >> $BASH_ENV
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/Rookout
      - persist_to_workspace:
          root: .
          paths:
            - workspace/VERSION

  python_test_27:
    docker:
      - image: us.gcr.io/rookout/python_test_27
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: make unit-tests

  pypy2_test:
    docker:
      - image: us.gcr.io/rookout/pypy_test
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: pypy -B setup.py build_ext --inplace
      - run: pypy -B -m unittest discover -s . -p "test_*.py" -v

  pypy3_test:
    docker:
      - image: us.gcr.io/rookout/pypy3_test
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: pypy -B setup.py build_ext --inplace
      - run: pypy -B -m unittest discover -s . -p "test_*.py" -v

  python_test_35:
    docker:
      - image: us.gcr.io/rookout/python_test_35
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: make unit-tests

  python_test_36:
    docker:
      - image: us.gcr.io/rookout/python_test_36
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: make unit-tests

  python_test_37:
    docker:
      - image: us.gcr.io/rookout/python_test_37
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - run: make unit-tests

  openjdk7_unittests:
    docker:
      - image: openjdk:7
    working_directory: ~/Rookout
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - *setup_env_var
      - run: export BCPROV_FILENAME=bcprov-ext-jdk15on-158.jar && wget --no-check-certificate "https://downloads.bouncycastle.org/java/${BCPROV_FILENAME}" && mv $BCPROV_FILENAME /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/ext && perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security && echo 	"security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | tee -a /etc/java-7-openjdk/security/java.security
      - run: cd rooks/jvm/rook && ./gradlew check

  openjdk8_unittests:
    docker:
      - image: openjdk:8
    working_directory: ~/Rookout
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - *setup_env_var
      - run: cd rooks/jvm/rook && ./gradlew check

  package_rook_java:
    docker:
      - image: us.gcr.io/rookout/java8
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/jvm/rook
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *load_gradle_cache
      - *auth_google
      - run: make build-rook
      - *save_gradle_cache
      - persist_to_workspace:
          root: ~/Rookout
          paths:
            - rooks/jvm/rook/build/libs/*.jar
      - store_artifacts:
          path: build/libs/

  rook_package_test_java7:
    docker:
      - image: openjdk:7
    working_directory: ~/Rookout/rooks/jvm/rook
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - *setup_env_var
      - run: apt-get update -qq && apt-get install -qq -y make --no-install-recommends
      - run: make package-test

  rook_package_test_java8:
    docker:
      - image: openjdk:8
    working_directory: ~/Rookout/rooks/jvm/rook
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - *setup_env_var
      - run: apt-get update -qq && apt-get install -qq -y make --no-install-recommends
      - run: make package-test

  rook_package_test_java7_alpine:
    docker:
      - image: openjdk:7-alpine
    working_directory: ~/Rookout/rooks/jvm/rook
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - run: apk update && apk add make --no-cache
      - run: . ~/Rookout/workspace/VERSION && make package-test

  rook_package_test_java8_alpine:
    docker:
      - image: openjdk:8-alpine
    working_directory: ~/Rookout/rooks/jvm/rook
    steps:
      - *checkout_default_wd
      - *load_gradle_cache
      - *setup_workspace
      - *setup_env_var
      - run: apk update && apk add make --no-cache
      - run: . ~/Rookout/workspace/VERSION && make package-test

  node_unit_tests:
    docker:
      - image: us.gcr.io/rookout/rooks_core_node
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/node/rook
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run:
          command: |
            . /usr/local/nvm/nvm.sh
            rm -rf node_modules/
            nvm use 4
            npm install
            npm run grpc
            npm run test
      - run:
          command: |
            . /usr/local/nvm/nvm.sh
            rm -rf node_modules/
            nvm use 6
            npm install
            npm run grpc
            npm run test
      - run:
          command: |
            . /usr/local/nvm/nvm.sh
            rm -rf node_modules/
            nvm use 8
            npm install
            npm run grpc
            npm run test
      - run:
          command: |
            . /usr/local/nvm/nvm.sh
            rm -rf node_modules/
            nvm use 10
            npm install
            npm run grpc
            npm run test

  package_rook_node:
    docker:
      - image: us.gcr.io/rookout/rooks_core_node
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/node/rook
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: . /usr/local/nvm/nvm.sh && printf "export PATH=%s:\$PATH\n" $(dirname $(nvm which 8)) >> $BASH_ENV
      - run: make build-node
      - persist_to_workspace:
          root: ~/Rookout
          paths:
            - rooks/node/rook/output/npm/rookout-*.tgz
            - rooks/node/rook/VERSION
      - store_artifacts:
          path: output/npm/rookout-*.tgz

  rook_package_test_node4:
    docker:
      - image: node:4
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: make -f ../rook/Makefile package-test

  rook_package_test_node6:
    docker:
      - image: us.gcr.io/rookout/node6
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: make -f ../rook/Makefile package-test

  rook_package_test_node8:
    docker:
      - image: node:8
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: make -f ../rook/Makefile package-test

  rook_package_test_node10:
    docker:
      - image: node:10
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: make -f ../rook/Makefile package-test
  
  rook_package_test_node_alpine:
    docker:
      - image: alpine:3.8
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - run:
          command: apk update && apk add nodejs npm bash ca-certificates make
          working_directory: /
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run: make -f ../rook/Makefile package-test
  
  rook_package_test_node_mac:
    macos:
      xcode: "9.4.1"
    working_directory: ~/Rookout/rooks/node/sample
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - *setup_env_var
      - run:
          command: |
            brew uninstall -f yarn node
            brew install node@8 make
            brew link --force --overwrite node@8
      - run: gmake -f ../rook/Makefile package-test

  rook_package_test_python2:
    docker:
      - image: us.gcr.io/rookout/python_test_27
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *setup_cache
      - *setup_workspace
      - *setup_env_var
      - run:  make -f rooks/python/Makefile test-package

  rook_package_test_python35:
    docker:
      - image: us.gcr.io/rookout/python_test_35
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *setup_cache
      - *setup_workspace
      - *setup_env_var
      - run: make -f rooks/python/Makefile test-package

  rook_package_test_python36:
    docker:
      - image: us.gcr.io/rookout/python_test_36
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *setup_cache
      - *setup_workspace
      - *setup_env_var
      - run: make -f rooks/python/Makefile test-package

  rook_package_test_python37:
    docker:
      - image: us.gcr.io/rookout/python_test_37
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *setup_cache
      - *setup_workspace
      - *setup_env_var
      - run: make -f rooks/python/Makefile test-package

  rook_package_test_pypy:
    docker:
      - image: us.gcr.io/rookout/pypy_test
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *setup_cache
      - *setup_workspace
      - *setup_env_var
      - run: make -f rooks/python/Makefile test-package-pypi

  package_rook_python:
    docker:
      - image: us.gcr.io/rookout/python_manylinux_x64
        <<: *docker_auth
    working_directory: ~/Rookout/rooks/python
    steps:
      - *setup_cache
      - *setup_workspace
      - *auth_google
      - run: make build-python-rook
      - persist_to_workspace:
          root: ~/Rookout
          paths:
            - rooks/python/dist
      - store_artifacts:
          path: dist/

  rook_push_artifacts:
    docker:
      - image: us.gcr.io/rookout/rooks_core_node:latest
        <<: *docker_auth
    working_directory: ~/Rookout
    steps:
      - *checkout_default_wd
      - *setup_workspace
      - run:
          command: |
            make push-artifacts
          working_directory: ~/Rookout/rooks/node/rook

notify:
  webhooks:
    - url: https://api.opsgenie.com/v1/json/circleci?apiKey=56e73c61-0325-439f-8845-5bcbd0a546e6

workflows:
  version: 2
  run-pipeline:
    jobs:
      - checkout_code
      