orbs:
  some-orb: rookout/rookout-node@0.0.1
  
jobs:
  my_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - some-orb/run_script:
          users_script: "node --trace-warnings --trace-sync-io --title=xxxxxxx ~/Rookout/test1.js"
          rookout_tags: "asdf;asdf2"
      
version: 2.1
workflows:
  main:
    jobs:
      - my_job