orbs:
  codecov: circleci/codecov-clojure@0.0.4
  my-orb:
    description: "A circle-ci orb that loads rookout-node to your program"
    parameters:
      rookout_token:
        type: string
      rookout_tags:
        type: string
      users_script:
        type: string
            
    executors:
      default:
        docker:
          - image: circleci/node:10
          
    commands:
      install_rook_if_needed:
        steps:
          - run: 
              command: | 
                echo "try {const rook = require('rookout');} catch (e) { process.exit(1); } process.exit(0);" > /tmp/testRookout.js
                if ! node /tmp/testRookout.js; then
                    sudo npm install --unsafe-perm -g rookout 
                fi
      run_users_script:
        steps:
          - run:
              command: | 
                echo <<rookout_token>>
                echo <<rookout_tags>>
                echo <<users_script>>
                node /tmp/testRookout.js
    jobs:
      myjob:
        executor: default
        steps:
          - install_rook_if_needed
          - run_users_script

version: 2.1
workflows:
  main:
    jobs:
      - my-orb/myjob:
          rookout_token: 1234
          rookout_tags: orb;benk
          users_script: node /tmp/testRookout.js
