
orbs:
  rookout-node:rookout/rookout-node@0.0.1
  
jobs:
  my_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - rookout-node/run_script:
          users_script: node --trace-warnings --trace-sync-io --title=xxxxxxx ~/Rookout/test1.js
      - rookout-node/run_script:
          users_script: node ~/Rookout/test1.js
      - rookout-node/run_script:
          users_script: ~/Rookout/test1.js       
      - rookout-node/run_script:
          users_script: ~/Rookout/test1.js param1 param2      
      
version: 2.1
workflows:
  main:
    jobs:
      - my_job