references:
  auth_google: &auth_google
    run:
      command: |
        sudo apt-get update && sudo apt-get install lsb-core 
        export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
        echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo apt-get update && sudo apt-get install google-cloud-sdk
        echo ${GOOGLE_AUTH} > gcp-key.json && gcloud auth activate-service-account --key-file gcp-key.json

orbs:
  rookout-node-orb:
    description: "A circle-ci orb that installs rookout-node to your job"
    jobs:
      execute:
        executor: default
        parameters:
          rookout_tags:
            type: string
            default: "$CIRCLE_PROJECT_REPONAME;$CIRCLE_JOB;circle-ci"
          users_script:
            type: string
            default: ""
        steps:
          - *auth_google
          - run:
              rookout_tags: <<parameters.rookout_tags>>
              users_script: <<parameters.users_script>>
            
    executors:
      default:
        docker:
          - image: circleci/node:10
# TODO:: silent all bash output          
    commands:
      run:
        parameters:
          rookout_tags:
            type: string
            default: "$CIRCLE_PROJECT_REPONAME;$CIRCLE_JOB;circle-ci"
          users_script:
            type: string
        steps:
            # this checkout is not needed
          - run: 
              # Install rook if needed
              command: | 
                if ! which rookout-node; then
                  gsutil cp gs://rookout-rooks-artifacts/rooks-nodejs/0.1.29/0.1.29+8335d4/rookout-0.1.29.tgz .
                  sudo npm install --unsafe-perm -g rookout-0.1.29.tgz
                fi
          - run:
              command: | 
                echo 'export ROOKOUT_ROOK_TAGS="<<parameters.rookout_tags>>"' >> $BASH_ENV
                source $BASH_ENV
                
                if [ "<<parameters.users_script>>" != "" ]; then
                    rookout-node <<parameters.users_script>>
                fi


jobs:
  my_secret_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - run: sudo mkdir -p /root/Rookout/workspace
      - *auth_google
      - rookout-node-orb/run:
          users_script: node ~/Rookout/test1.js
             
      
version: 2.1
workflows:
  main:
    jobs:
      - my_secret_job