orbs:
  orb-tools: circleci/orb-tools@2.0.0
  rookout-node: rookout/rookout-node@dev:${BRANCH_NAME:0.0.3}

jobs:
  my_job:
    docker:
      - image: circleci/node:10
    working_directory: ~/Temp
    steps:
      - checkout:
          path: ~/Rookout
      - rookout-node/run_script:
          users_script: "node --trace-warnings --trace-sync-io --title=xxxxxxx ~/Rookout/examples/example_app.js"
          rookout_tags: "asdf;asdf2"
      - rookout-node/run_script:
          users_script: "node ~/Rookout/examples/example_app.js"
      - rookout-node/run_script:
          users_script: "~/Rookout/examples/example_app.js"
      - rookout-node/run_script:
          users_script: "~/Rookout/examples/example_app.js p1 p2 p3"

  trigger_build:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          command: |
            curl -u ${CIRCLE_API_USER_TOKEN} -d build_parameters[CIRCLE_JOB]=deploy_docker https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>

version: 2.1
workflows:
  main:
    jobs:
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: rookout/rookout-node@dev:${BRANCH_NAME}
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
      - trigger_build:
          requires:
            - "orb-tools/publish"
      # increase version: (needs admin token)
      # circleci orb publish increment src/orb.yml rookout/rookout-node patch